[[redirects]]
  from = "/sitemap.rss"
  to = "https://rowcloxlszwnowlggqon.supabase.co/functions/v1/rss-feed"
  status = 200

[[redirects]]
  from = "/feed.xml"
  to = "https://rowcloxlszwnowlggqon.supabase.co/functions/v1/rss-feed"
  status = 200

[[redirects]]
  from = "/rss.xml"
  to = "https://rowcloxlszwnowlggqon.supabase.co/functions/v1/rss-feed"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "https://rowcloxlszwnowlggqon.supabase.co/functions/v1/sitemap"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
